---
- name: elasticsearch
  template: src=/home/bastion/template/elasticsearch.j2 dest=/etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch

- name: input
  template: src=/home/bastion/template/input.j2 dest=/etc/logstash/conf.d/output.conf

- name: filter
  template: src=/home/bastion/template/filter.j2 dest=/etc/logstash/conf.d/filter.conf

- name: output
  template: src=/home/bastion/template/output.j2 dest=/etc/logstash/conf.d/output.conf
  notify:
    - restart logstash


